//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductMaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderInfo
    {
        public int orderid { get; set; }
        public int prodqty { get; set; }
        public int totalamt { get; set; }
        public string paymentmode { get; set; }
        public string orderstatus { get; set; }
        public Nullable<int> pid { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
