//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductMaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.OrderInfoes = new HashSet<OrderInfo>();
        }
    
        public int PId { get; set; }
        public string PName { get; set; }
        public string PDesc { get; set; }
        public string PManu { get; set; }
        public decimal Price { get; set; }
        public string PCat { get; set; }
    
        public virtual ICollection<OrderInfo> OrderInfoes { get; set; }
    }
}
